default: &default
  status_schedules_worker:
    cron: "0 * * * *"
    class: "StatusSchedulesWorker"
    queue: "default"

development:
   status_schedules_worker:
    cron: "* * * * *"
    class: "StatusSchedulesWorker"
    queue: "default"

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
