default: &default
  status_schedule_worker:
    cron: "0 * * * *"
    class: "StatusScheduleWorker"
    queue: "default"

development:
   status_schedule_worker:
    cron: "* * * * *"
    class: "StatusScheduleWorker"
    queue: "default"

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
