test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: <%= Rails.application.secrets.gcs[:project] %>
  bucket: <%= Rails.application.secrets.gcs[:bucket] %>
  credentials:
    type: "service_account"
    project_id: <%= Rails.application.secrets.gcs[:credentials][:project_id] %>
    private_key_id:
      <%= Rails.application.secrets.gcs[:credentials][:private_key_id] %>
    private_key:
      <%= Rails.application.secrets.gcs[:credentials][:private_key]&.dump %>
    client_email:
      <%= Rails.application.secrets.gcs[:credentials][:client_email] %>
    client_id: <%= Rails.application.secrets.gcs[:credentials][:client_id] %>
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url:
      <%= Rails.application.secrets.gcs[:credentials][:client_url] %>
